name: docker-build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: 'echo $GITHUB_SHA > REVISION'
      - name: build
        run: "docker build -t docker.pkg.github.com/${{ github.repository }}/app:${GITHUB_SHA} -f Dockerfile ."
      - name: login
        run: "docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}"
      - name: tag
        run: "docker tag docker.pkg.github.com/${{ github.repository }}/app:${GITHUB_SHA} docker.pkg.github.com/${{ github.repository }}/app:latest"
      - run: "docker push docker.pkg.github.com/${{ github.repository }}/app:${GITHUB_SHA}"
      - run: "docker push docker.pkg.github.com/${{ github.repository }}/app:latest"
